{
 "title": "Analysis tool (Dashboard)",
 "time": { "from": "now-180d", "to": "now+8h" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "flask_test", "label": "flask_test", "query": "1081_創意學習_楊鎮華教師" },
   {
    "name": "contents_name",
    "label": "contents_name",
    "query": "SELECT distinct (cont.title)  FROM br_event_log as log, br_contents as cont, br_contents_directory as dir   WHERE  (cont.del_flag = 0) and  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' ;"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Learners (#)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  count(DISTINCT log.user_id) as 'Learners (#)',\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and\n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "Events (per person)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id) as 'Events / People',\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and\n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "All Events 頁數統計",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  log.page_no as 次數\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "ADD BOOKMARK (per pesron)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and log.operation_name = 'ADD BOOKMARK' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "ADD BOOKMARK 頁數統計",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  log.page_no as 次數\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD BOOKMARK' and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "NOT GET IT (per person)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and log.operation_name = 'NOTGETIT' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "NOT GET IT 頁數統計",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  log.page_no as 次數\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'NOTGETIT' and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  { "title": "Marker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Red Markers-重要 (per person)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name)  and log.marker_color = 'rgb(255,0,0)' and log.operation_name = 'ADD MARKER' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' and log.marker_text != ''"
    }
   ]
  },
  {
   "title": "Yellow Markers-不清楚 (per person)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name)  and log.marker_color = 'rgb(255,255,0)' and log.operation_name = 'ADD MARKER' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' and log.marker_text != ''"
    }
   ]
  },
  {
   "title": "「重要」  Marker_Text ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  log.operation_date,\n  muser.username,\n  log.user_id,\n  log.page_no,\n  log.marker_text as marker_text\n\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir, mdl_user as muser\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD MARKER' and log.contents_name IN ($contents_name) and log.marker_color = 'rgb(255,0,0)'\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'\n  and substring_index(log.user_id, '@', 1) = muser.id and log.marker_text != '';\n  \n  "
    }
   ]
  },
  {
   "title": "「不清楚」  Marker_Text ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  log.operation_date,\n  muser.username,\n  log.user_id,\n  log.page_no,\n  log.marker_text as marker_text\n\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir, mdl_user as muser\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD MARKER' and log.contents_name IN ($contents_name) and log.marker_color = 'rgb(255,255,0)'\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' and log.marker_text != ''\n  and substring_index(log.user_id, '@', 1) = muser.id;"
    }
   ]
  },
  {
   "title": "ADD MARKER 頁數統計",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  log.page_no as 次數\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD MARKER' and log.contents_name IN ($contents_name) \n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  { "title": "Memo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "ADD MEMO (per person)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and log.operation_name = 'ADD MEMO' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' and log.memo_text != \"\""
    }
   ]
  },
  {
   "title": "ADD_HW_MEMO (per person)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(cont.parent_id) / count(DISTINCT log.user_id),\n  $__timeGroupAlias(log.operation_date,$__interval)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and log.operation_name = 'ADD_HW_MEMO' and \n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'"
    }
   ]
  },
  {
   "title": "Memo_text",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  log.operation_date,\n  muser.username,\n  log.user_id,\n  log.page_no,\n  REPLACE(log.memo_text, ';:::nl:::;', ' ') as memo_text\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir, mdl_user as muser\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD MEMO' and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test' and log.memo_text != \"\"\n  and substring_index(log.user_id, '@', 1) = muser.id;"
    }
   ]
  },
  {
   "title": "ADD MEMO 頁數統計",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  log.page_no as 次數\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date) and operation_name = 'ADD MEMO' and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'\n"
    }
   ]
  },
  { "title": "Event statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Cumulative Sum Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  sum(count(cont.parent_id)) over(ORDER BY log.operation_date) as 'Cumulative Sum'\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir\nWHERE\n  $__timeFilter(operation_date)  and log.contents_name IN ($contents_name) and\n  cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'\n  \ngroup by 1"
    }
   ]
  },
  {
   "title": "Reading Completion",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log.operation_date,$__interval),\n  muser.username as metric,\n  count(DISTINCT log.page_no)\nFROM br_event_log as log, br_contents as cont, br_contents_directory as dir, mdl_user as muser\nWHERE\n  $__timeFilter(operation_date) and log.contents_name IN ($contents_name)\n  and cont.parent_id = dir.directory_id and cont.contents_id = log.contents_id and dir.name = '$flask_test'\n  and substring_index(log.user_id, '@', 1) = muser.id\n  \ngroup by muser.username;"
    }
   ]
  },
  { "title": "聯絡資訊", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "content": "\n# 圖表許願區\n***\n>有任何圖表的需求或問題請寄信至   聯絡信箱： bookrolltaiwan@gmail.com \n\n>估過後可能新增功能"
  }
 ]
}